#!/usr/bin/env python
import sys
import os
import numpy as np
import scipy as sp
import pandas as pd
import time

#Community simulator packages
from community_simulator import *
from community_simulator.usertools import *

#Community selection packages
from community_selection.usertools import *

input_csv = str(sys.argv[1]) # Input file name
row_number = int(sys.argv[2]) # Which row of experiment to run

assumptions = make_assumptions(input_csv, row_number)
params, params_simulation , params_algorithm, plate = prepare_experiment(assumptions)
simulate_community(params = params, params_simulation = params_simulation, params_algorithm = params_algorithm,plate = plate)
save_plate(assumptions, plate)     #Save plate (will onlys save if assumptions specify that)

