#!/usr/bin/env python
import sys
import os
import pandas as pd
from community_selection.usertools import *

input_csv = str(sys.argv[1]) # Input file name
row_number = int(sys.argv[2]) # Which row of experiment to run
output_file_name = str(sys.argv[3])

assumptions = make_assumptions(input_csv, row_number)
species_function = extract_species_function(assumptions)
species_function.to_csv(output_file_name, index = False)
print("\nGenerated per-capita species functions from: " + input_csv + "\nRow (0-based): " + str(row_number) + "\nOutput file name: " + output_file_name)
